/* Shared search and time-budget logic, independent of the interface. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.CatalogCore=api;})(typeof window!=='undefined'?window:globalThis,()=>{
 const aliases={hip:'hip',hips:'hip',pelvis:'hip',pelvic:'hip',glute:'glute',glutes:'glute',gluteal:'glute',butt:'glute',buttock:'glute',booty:'glute',ab:'core',abs:'core',abdominal:'core',abdominals:'core',abdomen:'core',core:'core',trunk:'core',shoulder:'shoulder',shoulders:'shoulder',deltoid:'shoulder',delt:'shoulder',scapular:'scapula',scapula:'scapula',lat:'lat',lats:'lat',latissimus:'lat',quad:'quad',quads:'quad',quadricep:'quad',quadriceps:'quad',hamstring:'hamstring',hamstrings:'hamstring',calf:'calf',calves:'calf',ankles:'ankle',feet:'foot',foot:'foot',thoracic:'thoracic',forearms:'forearm',resistance:'resistance',elastic:'band',bands:'band',band:'band',dowel:'bar',stick:'bar',dumbbells:'weight',dumbbell:'weight',weights:'weight',weight:'weight',stretching:'stretch',stretches:'stretch',flexibility:'mobility',flexible:'mobility',mobilization:'mobility',mobilise:'mobility',mobility:'mobility',beginner:'beginner',easy:'beginner',gentle:'light',light:'light',intermediate:'intermediate',moderate:'moderate',advanced:'advanced',hard:'high',strengthening:'strength',strength:'strength',pullup:'pull',pressup:'push',pushup:'push',press:'push',row:'pull',rowing:'pull',pulling:'pull'};
 const stop=new Set(['a','an','the','for','and','my','to','with','of','exercise','exercises','workout','workouts']);
 function tokens(text){return String(text||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/t[ -]?spine/g,'thoracic spine').replace(/no equipment|body[ -]?weight/g,'bodyweight').replace(/upper[ -]?back/g,'upper back thoracic').replace(/lower[ -]?back/g,'lower back lumbar').replace(/pull[ -]?ups?/g,'pullup').replace(/push[ -]?ups?|press[ -]?ups?/g,'pushup').replace(/shoulder blades?/g,'scapula').replace(/warm[ -]?up/g,'warmup').replace(/cool[ -]?down/g,'cooldown').split(/[^a-z0-9]+/).filter(t=>t&&!stop.has(t)).map(t=>aliases[t]||aliases[t.replace(/s$/,'')]||(t.length>4?t.replace(/s$/,''):t));}
 function close(a,b){if(a===b)return true;if(a.length<5||Math.abs(a.length-b.length)>1)return false;let i=0,j=0,edits=0;while(i<a.length&&j<b.length){if(a[i]===b[j]){i++;j++;continue;}if(++edits>1)return false;if(a.length>b.length)i++;else if(b.length>a.length)j++;else{i++;j++;}}return edits+(i<a.length||j<b.length?1:0)<=1;}
 function search(text,query){const q=tokens(query);if(!q.length)return true;const hay=new Set(tokens(text));return q.every(term=>hay.has(term)||[...hay].some(word=>word.startsWith(term)&&term.length>=3||close(term,word)));}
 function duration(steps,rounds=1){if(!steps.length)return 0;if(steps.some(s=>s.mode==='reps'))return null;return 3+steps.reduce((sum,s)=>sum+Number(s.work)+Number(s.rest),0)*rounds-Number(steps.at(-1).rest);}
 function fitting(groups,budgetMinutes){return groups.filter(g=>budgetMinutes===null||(duration(g.steps)!==null&&duration(g.steps)<=budgetMinutes*60)).sort((a,b)=>(duration(b.steps)??-1)-(duration(a.steps)??-1)||a.name.localeCompare(b.name));}
 function exerciseText(e,m){return [e.name,e.kind,e.equipment,e.area,m.target,m.difficulty,m.strain,...(m.tags||[]),...(m.regions||[]),...(e.variants||[]).map(v=>v.label)].join(' ');}
 function groupText(g,byId,metadata){return [g.name,g.kind,g.description,...(g.tags||[]),...(g.focus||[]),...g.steps.filter(s=>s.exercise!=='easy-walking').map(s=>exerciseText(byId[s.exercise],metadata[s.exercise]))].join(' ');}
 return {tokens,search,duration,fitting,exerciseText,groupText};
});
