const {webkit}=require(process.env.PLAYWRIGHT_MODULE||'/tmp/range-browser-check/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await webkit.launch();const page=await browser.newPage({viewport:{width:1180,height:820},isMobile:true,hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8766');await page.waitForSelector('.group-card');
async function checkSort(budget){const seconds=await page.locator('.group-card').evaluateAll(nodes=>nodes.map(n=>+n.dataset.seconds));assert(seconds.length);assert(seconds.every((s,i)=>s<=budget*60&&(!i||s<=seconds[i-1])));}
await checkSort(30);await page.waitForFunction(()=>[...document.querySelectorAll('.group-collage img')].slice(0,3).every(i=>i.complete&&i.naturalWidth));await page.screenshot({path:'/tmp/range-expanded-groups.png'});
await page.locator('[data-minutes="5"]').click();await checkSort(5);assert.equal(await page.locator('.group-card').count(),6);await page.locator('[data-minutes="30"]').click();await page.locator('[data-search="groups"]').fill('hips');assert(await page.locator('.group-card').count()>3);await checkSort(30);await page.locator('[data-search="groups"]').fill('back shoulders');assert(await page.locator('.group-card').count()>3);await page.locator('[data-search="groups"]').fill('');
await page.locator('[data-filter="kind"]').selectOption('Strength');await page.locator('.group-card').first().click();const initial=await page.locator('#setup-duration').innerText();assert(initial.includes('29 min'));assert.equal(await page.locator('.block-heading').count(),3);assert((await page.locator('.setup-step').first().innerText()).includes('300s'));await page.locator('[data-setup-mode="reps"]').click();assert((await page.locator('.setup-step').first().innerText()).includes('300s'));assert((await page.locator('.setup-step').last().innerText()).includes('300s'));await page.locator('[data-setup-mode="saved"]').click();await page.locator('#begin-workout').click();await page.waitForTimeout(3300);assert.equal(await page.locator('#phase-label').innerText(),'WARM-UP');assert(await page.locator('#instruction-guide').isVisible());assert(await page.locator('#workout-video').isHidden());await page.screenshot({path:'/tmp/range-expanded-warmup.png'});await page.locator('#end-workout').click();await page.locator('#confirm-end').click();
await page.locator('[data-page="exercises"]').click();await page.locator('[data-search="exercises"]').fill('calves');assert(await page.locator('.exercise-card').count()>=3);await page.locator('[data-search="exercises"]').fill('wall pushup');assert.equal(await page.locator('.exercise-card').count(),1);assert(await page.locator('.photo-badge').isVisible());await page.locator('.exercise-open').click();assert(await page.locator('.photo-guide img').isVisible());await page.locator('#begin-workout').click();await page.waitForTimeout(3300);assert(await page.locator('#workout-photo').isVisible());assert(await page.locator('#workout-video').isHidden());assert(await page.locator('#workout-photo').evaluate(i=>i.complete&&i.naturalWidth>0));await page.screenshot({path:'/tmp/range-expanded-photo.png'});await page.locator('#end-workout').click();await page.locator('#confirm-end').click();
await page.locator('[data-search="exercises"]').fill('sholders');assert(await page.locator('.exercise-card').count()>10);await page.locator('[data-search="exercises"]').fill('bar shoulders');assert(await page.locator('.exercise-card').count()>5);await page.locator('[data-search="exercises"]').fill('no equipment abs');assert(await page.locator('.exercise-card').count()>3);
await page.locator('[data-page="groups"]').click();await page.selectOption('[data-filter="kind"]','');await page.setViewportSize({width:820,height:1180});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/tmp/range-expanded-portrait.png'});
await page.locator('#time-budget').fill('15');await checkSort(15);await page.reload();assert.equal(await page.locator('#budget-value').innerText(),'15 min');await checkSort(15);await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
assert.deepEqual(errors,[]);console.log('PASS WebKit: global time ordering, 5/15/30-minute limits, budget persistence, group anatomy search, workout types, phase overview, preserved warm-up in rep mode, instruction/photo playback, synonyms and typo search, iPad portrait/landscape and phone layout.');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
